services:
  albums.db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=albumsdb
    volumes:
      - albumsdbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -uroot -proot albumsdb -e 'select 1'"
      timeout: 20s
      interval: 10s
      retries: 10

volumes:
  albumsdbdata: